[package]
name = "rgba_builder"
version = "1.0.0"
edition = "2021"
authors = ["Louise"]

[dependencies]
log = "~0.4.0"
rgba_common = { path = '../rgba_common' }
rgba_dmg_core = { path = '../rgba_dmg_core' }
rgba_gba_core = { path = '../rgba_gba_core' }
